### ISSUE TITLE
Inventory issue

### ISSUE THREAD

**Issue by EagLeTaLoN713** [VORPCORE/VORP-Housing#12]
Inventory on created houses don’t seem to work. Created purchasable house in script but unable to get inventory function.

**Comment by SimpleSandman** [comment]
I'm currently working on fixing a bunch of issues right now. You can track them in this PR #11 .
If you wouldn't mind helping me test some of my changes, that would be awesome!

**Comment by EagLeTaLoN713** [comment]
I’ll do that tomorrow. Glad this is being reworked it certainly needs some love

**Comment by SimpleSandman** [comment]
This can be closed as this was fixed from #11
