### ISSUE TITLE
Cannot implicitly convert type 'int' to 'uint' / Breaks The Script.

### ISSUE THREAD

**Issue by JaroSound** [VORPCORE/VORP-Housing#4]
Today I had such an error. So the script stopped working. It appeared over time when I had more than 1 house purchased. In my db everythink looks normal :(

Full Errol:
"Cannot implicitly convert type 'int' to 'uint'. An explicit conversion exists (are you missing a cast?)"

Server Version: 2619 Windows

**Comment by rubi216** [comment]
Can you send a photo?

**Comment by JaroSound** [comment]
![1](https://user-images.githubusercontent.com/19697423/95658421-85fdf380-0b1a-11eb-9e4e-f2929ffe59fd.png)
![2](https://user-images.githubusercontent.com/19697423/95658422-86968a00-0b1a-11eb-9412-6c7fe0a6a25a.png)

**Comment by JaroSound** [comment]
Error started after full server restart.

**Comment by BulgaRpl** [comment]
I can confirm that...
Have the same problem and, from what I know, there are more ppls with this problem.

I also reported it on Discord before.

**Comment by rubi216** [comment]
I meant a photo of the error, not the database

**Comment by JaroSound** [comment]
![2](https://user-images.githubusercontent.com/19697423/95659730-5a333b80-0b23-11eb-9266-00e3f28edad3.png)

When i get this error houses won't load on the map, there are no houses blips. Its like the script is not working after that at all. After cleaning the DB, the problem disappears, it reappears when I have more houses purchased in the DB. Then when i restart my serwer the problem appears again.

**Comment by BulgaRpl** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/69915160/95660057-a5e6e480-0b25-11eb-9f2e-5ef41b90343f.png)

Same here, after a player connect to server. Houses wont load at all after this happening.

**Comment by BulgaRpl** [comment]
![2](https://user-images.githubusercontent.com/69915160/95660148-30c7df00-0b26-11eb-9cad-706a1d626624.png)

This happens exactly after selecting the character. After reconnect screen.

**Comment by BulgaRpl** [comment]
I think I found what causes this problem.
I way buing houses 1 by 1 and restarting the server all time. (CUZ I HAVE NO REAL LIFE XD IT TOOK A WHILE)

When u buy:

```
    {
      "Id": 2,
      "InteriorName": "che_maincabin_occupied",
      "Name": "Window Rock Farm (Wkrótce na Licytacji)",
      "Price": 999999.0,
      "DoorsStatus": [ -398.143, 1722.365, 216.4293 ],
      "Doors": [
        [ -398.64300537109, 1722.3649902344, 215.42929077148, 19.642013549805 ],
        [ -389.57995605469, 1730.2189941406, 215.41470336914, 109.72333526611 ]
      ],
      "Inventory": [ -394.63, 1726.35, 216.48, 1.5 ],
      "MaxWeight": 380
    },

```
It appears and script wont work. There is somethink wrong with this house. Try to buy this house @rubi216 and see what happend after restart and connect 👍

**Comment by Artzalez** [comment]
**Fixed!** 👍
Thank you for reporting the problem to us in detailed
Re-Download:
https://github.com/VORPCORE/VORP-Housing/releases/tag/JohnMarston
