### ISSUE TITLE
Multicharacter Bug? / When i Buy a Apartment or Hotel, i can acces it on both my characters.

### ISSUE THREAD

**Issue by BulgaRpl** [VORPCORE/VORP-Housing#6]
When i Buy a Apartment or Hotel, i can acces it on both my characters.

**Comment by JaroSound** [comment]
Same Problem.

**Comment by JaroSound** [comment]
I think everyone can enter a room that i buy. Someone just bought a room aand everyone can acces it after restart.

**Comment by BulgaRpl** [comment]
What i have noticed now, when the owner enters the room/house and leaves session everyone can enter this room and acces inventory but the inventory is empty for them.

**Comment by BulgaRpl** [comment]
correction, it is enough for the owner to connect to the server and everyone can use the room after he just connected.

**Comment by JaroSound** [comment]
Same problem for Houses... After server restart, Everyone Has the keys and can open someones house and acces inventory. :(

**Comment by JaroSound** [comment]
Any fix planned?
