### ISSUE TITLE
Anyone Can use House or Apartment doors

### ISSUE THREAD

**Issue by NeoGaming22** [VORPCORE/VORP-Housing#7]
Had a few reports of this already, but can confirm as well starting today users were able to open other peoples homes. using thier locks even tho they didnt own it

**Comment by skatesdsq** [comment]
Same here . this is the second open issue about it

**Comment by rc2pc2** [comment]
From what I've been able to see on my server this is true, but it's also true that they are not able to access the housing inventory (which is the most important thing, imho)

**Comment by JaroSound** [comment]
https://github.com/VORPCORE/VORP-Housing/issues/6

**Comment by BulgaRpl** [comment]
> but it's also true that they are not able to access the housing inventory
They can use inventory, but it freezes, so they can't use it.

I hope that the fix will come out soon...
